/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agileseven.codereview.client.views;

import com.agileseven.codereview.client.ServiceConsumer;
import com.agileseven.codereview.client.DTO.CodeDTO;
import com.agileseven.codereview.client.DTO.ReviewDTO;
import com.agileseven.codereview.client.utils;
import java.util.Date;
import javax.swing.JOptionPane;
import org.json.JSONObject;


/**
 *
 * @author Jin Xutong
 * TODO: TextArea for code reviewing and button for
 *       approved or not
 *
 */
public class FrameReview extends javax.swing.JFrame {
//------------------------------------modified------------------------------------
    private int codeId;
    ServiceConsumer service = new ServiceConsumer();
    private Date startDate;
    private Date endDate;
    /**
     * Creates new form JFrameReviewApprove
     */
    public FrameReview(int codeId) {
        this.codeId = codeId;
        initComponents();
        CodeDTO code = service.getCodeById(codeId);
        textArea_ShowCode.setText(code.getCodeText());
        startDate = new Date();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_ConfirmApproved = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_ShowCode = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButton_ConfirmApproved.setForeground(new java.awt.Color(0, 204, 0));
        jButton_ConfirmApproved.setText("Confirm");
        jButton_ConfirmApproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmApprovedActionPerformed(evt);
            }
        });

        textArea_ShowCode.setColumns(20);
        textArea_ShowCode.setRows(5);
        jScrollPane1.setViewportView(textArea_ShowCode);

        jButton1.setForeground(new java.awt.Color(204, 0, 51));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_ConfirmApproved, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ConfirmApproved, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ConfirmApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmApprovedActionPerformed
        
        endDate = new Date();
        
        JSONObject review = new JSONObject();
        
        review.put("codeId", this.codeId);
        review.put("reviewerId",3);
        review.put("approved",1);
        review.put("startTime", utils.convertDatetoString(this.startDate,"yyyy-M-dd hh:mm:ss"));
        review.put("submitTime", utils.convertDatetoString(this.endDate,"yyyy-M-dd hh:mm:ss"));
       
        int review_id = service.addReview(review.toString());
        
        if(review_id != -1){
            JOptionPane.showMessageDialog(this,"File has been successfully reviewed. Review_id : "+ review_id, "Success", JOptionPane.PLAIN_MESSAGE);
            this.setVisible(false);
            new UnreadCodeList().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Unable to save review. Please try later.", "Error", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            new UnreadCodeList().setVisible(true);
        
        }
    }

/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameReview(1).setVisible(true);
            }
        });
    
    }//GEN-LAST:event_jButton_ConfirmApprovedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new UnreadCodeList().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_ConfirmApproved;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea_ShowCode;
    // End of variables declaration//GEN-END:variables
}
