/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agileseven.codereview.client.views;


/**
 *
 * @author Jin Xutong
 * TODO: TextArea for code reviewing and button for
 *       approved or not
 *
 */
public class JFrameReviewApprove extends javax.swing.JFrame {
//------------------------------------modified------------------------------------
    private int approved;
    /**
     * Creates new form JFrameReviewApprove
     */
    public JFrameReviewApprove(int approved) {
        initComponents();
        this.approved = approved;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_ConfirmApproved = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_ShowCode = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_ConfirmApproved.setText("Confirm");
        jButton_ConfirmApproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmApprovedActionPerformed(evt);
            }
        });

        textArea_ShowCode.setColumns(20);
        textArea_ShowCode.setRows(5);
        jScrollPane1.setViewportView(textArea_ShowCode);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_ConfirmApproved, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton_ConfirmApproved, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ConfirmApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmApprovedActionPerformed
        // TODO add your handling code here:
         /*
         //Put approve state
         String reqJsonStr = "???";
         headers.setContentType(MediaType.APPLICATION_JSON);
         HttpEntity<String> entity = new HttpEntity<String>(reqJsonStr,headers);
         ResponseEntity<Map> resp = 
                 restTemplate.exchange("???", 
                         HttpMethod.PUT, entity, Map.class);
         */
         if(jButton_ConfirmApproved.isSelected()){
            approved = 1;
        }else{
            approved = 0;
        }


    }//GEN-LAST:event_jButton_ConfirmApprovedActionPerformed

    public void notifyObserver() {
        textArea_ShowCode.setText("");
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ConfirmApproved;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea_ShowCode;
    // End of variables declaration//GEN-END:variables
}
